package dev.trindadedev.visualcompose.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

public val LightColorScheme: ColorScheme =
    ColorScheme(
        primary = Color(0xFF006875),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF95F0FF),
        onPrimaryContainer = Color(0xFF001F24),
        inversePrimary = Color(0xFF75D5E5),
        secondary = Color(0xFF4A6367),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCDE7ED),
        onSecondaryContainer = Color(0xFF051F23),
        tertiary = Color(0xFF4C5D8B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFD9E2FF),
        onTertiaryContainer = Color(0xFF031943),
        background = Color(0xFFF1FBFE),
        onBackground = Color(0xFF141D1E),
        surface = Color(0xFFF1FBFE),
        onSurface = Color(0xFF141D1E),
        surfaceVariant = Color(0xFFDBE4E6),
        onSurfaceVariant = Color(0xFF3F484A),
        surfaceTint = Color(0xFF006875),
        inverseSurface = Color(0xFF293233),
        inverseOnSurface = Color(0xFFE9F3F4),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF6E7879),
        outlineVariant = Color(0xFFBFC8CA),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF1FBFE),
        surfaceDim = Color(0xFFD2DCDE),
        surfaceContainer = Color(0xFFE5F0F2),
        surfaceContainerHigh = Color(0xFFE0EAEC),
        surfaceContainerHighest = Color(0xFFDBE4E6),
        surfaceContainerLow = Color(0xFFEBF6F8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
    )

public val DarkColorScheme: ColorScheme =
    ColorScheme(
        primary = Color(0xFF75D5E5),
        onPrimary = Color(0xFF00363E),
        primaryContainer = Color(0xFF004F59),
        onPrimaryContainer = Color(0xFF95F0FF),
        inversePrimary = Color(0xFF006875),
        secondary = Color(0xFFB2CBD0),
        onSecondary = Color(0xFF1C3439),
        secondaryContainer = Color(0xFF334A4F),
        onSecondaryContainer = Color(0xFFCDE7ED),
        tertiary = Color(0xFFB4C5F9),
        onTertiary = Color(0xFF1C2F59),
        tertiaryContainer = Color(0xFF344571),
        onTertiaryContainer = Color(0xFFD9E2FF),
        background = Color(0xFF0B1517),
        onBackground = Color(0xFFDBE4E6),
        surface = Color(0xFF0B1517),
        onSurface = Color(0xFFDBE4E6),
        surfaceVariant = Color(0xFF3F484A),
        onSurfaceVariant = Color(0xFFBFC8CA),
        surfaceTint = Color(0xFF75D5E5),
        inverseSurface = Color(0xFFDBE4E6),
        inverseOnSurface = Color(0xFF293233),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF899294),
        outlineVariant = Color(0xFF3F484A),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF323B3D),
        surfaceDim = Color(0xFF0B1517),
        surfaceContainer = Color(0xFF192123),
        surfaceContainerHigh = Color(0xFF232B2D),
        surfaceContainerHighest = Color(0xFF2E3638),
        surfaceContainerLow = Color(0xFF141D1E),
        surfaceContainerLowest = Color(0xFF041012),
    )
